- lib/activity_notification/roles/acts_as_notifiable.rb
When tracked_option was expanded into the argument list, if non-empty it pushed extraneous arguments
> Fixed error calling #notify for callbacks

- lib/activity_notification/orm/active_record/notification.rb
When using a custom table name (`notification_table_name`) the calls to `unopened_group_member_notifier_count` and `opened_group_member_notifier_count` failed as they fall back to the default name. This should fix that.
> Ensure configured table name is respected

- lib/generators/templates/controllers/README
When wishing to use a custom notification controller, the controller name must be passed to the singular hash option `controller` in the `routes.rb` file.
See https://github.com/simukappu/activity_notification/blob/master/lib/activity_notification/rails/routes.rb for more details.
(Previously, the README for controllers template suggested passing the controller name to the **plural** hash option `controllers` -- but that does not work)
> Fix README for controllers template

- lib/activity_notification/renderable.rb
- spec/helpers/view_helpers_spec.rb
I was exploring the render options and noticed passing the `i18n` param (to bypass the partial rendering) was throwing a MissingTemplate error, this should get it more in line with the call in https://github.com/simukappu/activity_notification/compare/master...markedmondson:fix-i18n-render?expand=1#diff-2f0a0e25204a71bd80c120a836129462R155
> Update render method to use plain

- README.md
I suppose the way of activity_notification looking for email template is not exact as the readme file. The view file name is just the last word of the key split by the period, not started with an underscore. I come across the problem in my project, and trace the code, finally solve it by changing the view file name.
> change the readme about the email templates

- README.md
- lib/activity_notification/mailers/helpers.rb
- spec/mailers/mailer_spec.rb
I have a use case in my project that requires custom `Reply-To` & `Message-ID` headers on outgoing email notifications for certain notifiables (these values are parsed when a reply is received and allows users to reply to threads via email).
Currently I have a custom mailer and notification hooks for this that mail notifications when a reply is posted, but activity_notification could handle the notification completely if I could set these options myself.
I created this patch to work similarly to how overriding the email subject currently works, and perhaps it would be beneficial for others too if you think this is a useful feature that could be merged upstream. I'm looking forward to any comments you may have. Thanks!
> Configurable from, reply_to and message_id mailer headers

- lib/activity_notification/apis/notification_api.rb
- spec/concerns/apis/notification_api_spec.rb
**Issue #, if available**:
`:pass_full_options` is not included in `available_options` which makes it persisted in the database if `:pass_full_options` is used when calling `notify`
> Add pass_full_options to available_options

- lib/activity_notification.rb
**Issue #, if available**:
#124 
Fix `config.eager_load = true` crash by adding back `autoload VERSION` as it's used in [`apidocs_controller.rb`](https://github.com/simukappu/activity_notification/blob/master/app/controllers/activity_notification/apidocs_controller.rb#L9)
> Fix eager_load by autoloading VERSION

- lib/activity_notification/orm/mongoid/subscription.rb
- spec/models/subscription_spec.rb
Issue #126 :
add spec to proof key validation error with mongoid
error is make only with commands like `AN_TEST_DB=mongodb AN_ORM=mongoid bundle exec rspec`
> add erroned spec

- docs/Functions.md
When creating a default template, according to docs, one should create a partial e.g. `_default.html.erb`, when really it should 
be `default.html.erb`, otherwise the email is not sent due to template compilation error.
> Update docs for default email templates

- lib/activity_notification/models/concerns/swagger/notification_schema.rb
- lib/activity_notification/models/concerns/swagger/subscription_schema.rb
**Issue #146 
The following hash syntax being used in `notification_schema.rb` and `subscription_schema.rb` schemas causes a syntax error on `ruby 2.1`
```
$ruby -e "h = {\"key\": \"value\"}; puts h"
-e:1: syntax error, unexpected ':', expecting =>
h = {"key": "value"}; puts h
^
-e:1: syntax error, unexpected '}', expecting end-of-input
h = {"key": "value"}; puts h
```
Using the following syntax we get the hash as expected with a symbol as the key: 
```
ruby -e "h = {key: \"value\"}; puts h"
{:key=>"value"}
```
> Fix hash syntax in swagger schemas

- .travis.yml
- lib/activity_notification/orm/active_record.rb
- lib/activity_notification/orm/active_record/notification.rb
**Issue #122**
Fix the deprecation warnings for ruby 2.7
> Fix ruby 2.7 deprecation warnings

- .travis.yml
- lib/activity_notification/common.rb
- lib/activity_notification/orm/active_record.rb
- lib/activity_notification/orm/active_record/notification.rb
- lib/activity_notification/renderable.rb
- spec/concerns/common_spec.rb
- spec/concerns/renderable_spec.rb
- spec/controllers/controller_spec_utility.rb
Resolve #122 
**Summary**
This PR fixes all deprecation warnings appearing in specs for ruby 2.7. 
(For easier work I also pulled @szechyjs commit into this PR, we should probably merge https://github.com/simukappu/activity_notification/pull/137 first and then I will rebase this PR. @simukappu is it okay with you?)
> Remove Ruby 2.7 deprecation warnings

- lib/activity_notification/orm/active_record/notification.rb
Just clean up the code.
ref:
* Add `{ optional: true }` when Rails 5
- 4459cabb2005d15849b5c1de01b86329f58cad2a
* Add double splat
- f989d7590097b6e52783e4bc822fa6ddd94de347
* Drop Rails 4.2 Support
- 181c259eded50752ab270e1c421b82472497c74b
> Remove redundant double splat

- app/controllers/activity_notification/subscriptions_controller.rb
- app/views/activity_notification/subscriptions/default/_form.html.erb
- app/views/activity_notification/subscriptions/default/_notification_keys.html.erb
- app/views/activity_notification/subscriptions/default/_subscription.html.erb
- app/views/activity_notification/subscriptions/default/index.html.erb
- app/views/activity_notification/subscriptions/default/show.html.erb
- docs/Functions.md
- lib/activity_notification/apis/subscription_api.rb
- lib/activity_notification/config.rb
- lib/activity_notification/models/concerns/subscriber.rb
- lib/activity_notification/models/concerns/target.rb
- lib/activity_notification/orm/dynamoid/subscription.rb
- lib/activity_notification/orm/mongoid/subscription.rb
- lib/generators/templates/activity_notification.rb
- spec/concerns/apis/subscription_api_spec.rb
- spec/concerns/models/subscriber_spec.rb
- spec/rails_app/config/initializers/activity_notification.rb
**Issue #, if available**: #159
I added two new entry to `ActivityNotification::Config`, `subscribe_to_email_as_default` to change default subscriptions for emails (if you want to differ from `subscribe_as_default`) and `subscribe_to_optional_targets_as_default` to change default subscriptions for optional targets. Then I went through the gem, looked for usages of `subscribe_as_default` and changed them to use the new configs. After introducing the new defaults to every reasonable place, the tests remained green (that was the expected result as the new configs have a fallback to the common default)
I still need to do a few steps to finish the PR, but an initial review would be nice
> Configure default subscriptions for emails and optional targets

- lib/activity_notification/apis/notification_api.rb
- spec/concerns/apis/notification_api_spec.rb
**Issue #155**
Don't silence OptionalTarget exceptions because when using the Notification#notify API there's no way to access the errors and they are completely lost (other than reaching into Rails.logger.error).
Better is to allow the user to rescue their own code so they can perform the necessary result. [If they just want to silently skip](https://github.com/simukappu/activity_notification/issues/103), then `next` is their friend.
> Don’t silence optional target exceptions

- .github/workflows/build.yml
- Gemfile
- activity_notification.gemspec
- gemfiles/Gemfile.rails-7.1
- spec/concerns/renderable_spec.rb
- spec/spec_helper.rb
For #173.
I would respectfully suggest that 6.0 and lower be dropped soon.  Rails 7.2 is in beta and 8 is in heavy development.  This would also drop dynamoid support.
> Rails 7.1 support

- lib/activity_notification/orm/active_record/notification.rb
- lib/activity_notification/orm/active_record/subscription.rb
**Issue #178**:
Rails deprecated passing the type as a second argument and no longer defaults to YAML as the default serializer:
https://github.com/rails/rails/blob/77dfa65392e672ac83ced68cda37d5770c16ea6c/activerecord/CHANGELOG.md?plain=1#L1262
https://github.com/rails/rails/blob/77dfa65392e672ac83ced68cda37d5770c16ea6c/activerecord/CHANGELOG.md?plain=1#L1282
I did not realize this until I did config.load_defaults 7.1 .  It may work in non-engine scenarios (see related rails issue https://github.com/rails/rails/issues/52336), but this solves it for 7.1 and the upcoming 7.2
#173 original PR
> fix serialize arguments for Rails 7.1+

- .github/workflows/build.yml
- Gemfile
- activity_notification.gemspec
- gemfiles/Gemfile.rails-8.0
- lib/activity_notification/rails/routes.rb
> Rails 8.0 support

- README.md
- docs/Setup.md
- lib/activity_notification/apis/notification_api.rb
- spec/concerns/apis/notification_api_spec.rb
**Issue #186**:
Scenario:
GIVEN I have an unopened notification
WHEN I delete the notifiable associated with the notification, but the notification still exists
AND I click on the notification
THEN the notification should be marked as opened
> Add skip_validation option to open! method for notification handling
